[package]
name = "monitor"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
sysinfo = { workspace = true }
battery = { workspace = true }
